---
swagger: "2.0"
info:
  description: "This is a server to get Tweets."
  version: "1.0.0"
  title: "Twitter Scraper"
schemes:
- "https"
- "http"
paths:
  /tweets_by_hashtag:
    get:
      tags:
      - "tweets"
      summary: "Scrape tweets using hashtag"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "tweets_using_hashtag"
      produces:
      - "application/json"
      parameters:
      - name: "hashtag"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        type: "string"
        items:
          type: "string"
          default: ""
      - name: "number_of_tweets"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: false
        type: "string"
        items:
          type: "string"
          default: ""
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/tweets"
        "400":
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.tweets_controller"
  /user_tweets:
    get:
      tags:
      - "tweets"
      summary: "Scrape user tweets"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "user_tweets"
      produces:
      - "application/json"
      parameters:
      - name: "userID"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        type: "string"
        items:
          type: "string"
          default: ""
      - name: "number_of_tweets"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: false
        type: "string"
        items:
          type: "string"
          default: ""
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            items:
              $ref: "#/definitions/tweets"
        "400":
          description: "Invalid status value"
      x-swagger-router-controller: "swagger_server.controllers.tweets_controller"
definitions:
  tweets:
    type: "object"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
